import { useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { toast } from "sonner";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { Copy, Download, FileText, Plus, Printer } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { useConsultation } from "@/context/ConsultationContext";
import { StatusBadge } from "@/components/StatusBadge";

export default function FinalReport() {
  const navigate = useNavigate();
  const { finalReport, threadId, reset } = useConsultation();

  useEffect(() => {
    if (!finalReport) navigate("/");
  }, [finalReport, navigate]);

  const handleCopy = async () => {
    if (!finalReport) return;
    try {
      await navigator.clipboard.writeText(finalReport);
      toast.success("Report copied to clipboard");
    } catch {
      toast.error("Failed to copy");
    }
  };

  const handleDownload = () => {
    if (!finalReport) return;
    const blob = new Blob([finalReport], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `mediflow-report-${threadId?.slice(0, 8) ?? "session"}.md`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Report downloaded");
  };

  const handleNew = () => {
    reset();
    navigate("/");
  };

  return (
    <div className="min-h-screen gradient-subtle px-6 py-10 lg:py-14">
      <div className="max-w-4xl mx-auto animate-fade-in">
        <div className="flex flex-wrap items-start justify-between gap-4 mb-8 no-print">
          <div>
            <p className="text-sm font-semibold text-primary uppercase tracking-wider">Step 4 of 4</p>
            <h1 className="font-display text-3xl md:text-4xl font-bold mt-1">Final Medical Report</h1>
            <p className="text-muted-foreground mt-2">
              Complete clinical workflow output, validated by physician review.
            </p>
          </div>
          <StatusBadge variant="complete" />
        </div>

        <div className="flex flex-wrap gap-2 mb-5 no-print">
          <Button onClick={handleDownload} className="gradient-hero border-0 shadow-soft hover:opacity-90">
            <Download className="h-4 w-4" /> Download Report
          </Button>
          <Button variant="outline" onClick={handleCopy}>
            <Copy className="h-4 w-4" /> Copy
          </Button>
          <Button variant="outline" onClick={() => window.print()}>
            <Printer className="h-4 w-4" /> Print
          </Button>
          <Button variant="outline" onClick={handleNew}>
            <Plus className="h-4 w-4" /> New Consultation
          </Button>
        </div>

        <Card className="bg-card border-border shadow-elegant overflow-hidden">
          {/* Report header */}
          <div className="px-8 py-6 border-b border-border gradient-card flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="h-11 w-11 rounded-xl gradient-hero flex items-center justify-center shadow-soft">
                <FileText className="h-5 w-5 text-white" />
              </div>
              <div>
                <h2 className="font-display font-bold text-lg">Clinical Consultation Report</h2>
                <p className="text-xs text-muted-foreground">
                  Generated by MediFlow AI · {new Date().toLocaleString()}
                </p>
              </div>
            </div>
            <div className="text-right text-xs text-muted-foreground">
              <p className="font-semibold text-foreground">Session</p>
              <p className="font-mono">{threadId?.slice(0, 12)}…</p>
            </div>
          </div>

          {/* Report body */}
          <div className="px-8 py-10 lg:px-12 lg:py-12">
            <div className="report-body prose prose-slate max-w-none text-[15px] prose-headings:font-display prose-headings:font-bold prose-h1:text-2xl prose-h2:text-xl prose-h3:text-lg prose-a:text-primary prose-strong:text-foreground prose-table:text-sm">
              {finalReport ? (
                <ReactMarkdown remarkPlugins={[remarkGfm]}>{finalReport}</ReactMarkdown>
              ) : (
                "No report content available."
              )}
            </div>
          </div>

          <div className="px-8 py-4 border-t border-border bg-secondary/40 text-xs text-muted-foreground flex items-center justify-between">
            <span>End of report</span>
            <span>MediFlow AI · LangGraph orchestration</span>
          </div>
        </Card>
      </div>
    </div>
  );
}
